### PR TITLE
Generic function attributes

### PR DESCRIPTION
**Pull request by AlexVlx**

### CODE REVIEW

**Comment by yxsamliu** [comment]
Basically LGTM. Can you add a test to hcc?

**Review by kzhuravl — APPROVED** [review]
LGTM. Should these be committed to trunk as well?

**Comment by whchung** [comment]
@kzhuravl i did asked @AlexVlx to submit this patch to clang trunk as well as it seems to be generic enough. OpenCL could benefit from this patch too I think.

**Comment by yxsamliu** [comment]
I agree this is better submitted to trunk for review.

**Comment by kzhuravl** [comment]
@AlexVlx, review should be posted to phabricator as well https://llvm.org/docs/Phabricator.html . Then submitted to trunk. Thanks.

**Pull request merged**
