### PR TITLE
Merge amd-common into clang_tot_upgrade 20170908

### PR DESCRIPTION
**Pull request by aaronenyeshi**

### CODE REVIEW

**Comment by whchung** [comment]
@aaronenyeshi i only see `clang` and `llvm` PRs. would you update `lld`, `clang-tools-extra`, `rocdl`, `compiler-rt` as well?

**Comment by aaronenyeshi** [comment]
Yes, it is here:
o	https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/80
o	https://github.com/RadeonOpenCompute/lld/pull/27
o	https://github.com/RadeonOpenCompute/llvm/pull/101
o	https://github.com/RadeonOpenCompute/compiler-rt/pull/8
o	https://github.com/RadeonOpenCompute/clang-tools-extra/pull/4
Rocdl won't need merge since we take master

**Comment by whchung** [comment]
thx. for some reason i wasn't receiving notifications about them.

**Comment by aaronenyeshi** [comment]
I think we can merge these, or Alex's version

**Comment by aaronenyeshi** [comment]
Merged later commit

**Pull request closed without merging**
