### PR TITLE
Merge 20171019

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by whchung** [comment]
@yxsamliu could you provide `make test` results here.

**Comment by yxsamliu** [comment]
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 1154.16s
********************
Failing Tests (2):
    HCC :: Unit/Copy/copy.cpp
    HCC :: Unit/HC/const-global-var.cpp

  Expected Passes    : 735
  Expected Failures  : 32
  Unexpected Failures: 2

I got two failures. However they are not due to this merge since I got the same failures without the merge.

**Comment by whchung** [comment]
@yxsamliu could you check why these 2 cases are failing on your machine? On Jenkins CI they are never failing to my understanding. @scchan could you help chime in.

**Comment by scchan** [comment]
@whchung I couldn't reproduce those 2 failures with the current hcc tip on my machine either

**Comment by yxsamliu** [comment]
I will try to build from scratch and see if there are still failures. BTW what rocm-master build did you use?

**Comment by scchan** [comment]
I just used the current tip of clang_tot_upgrade  https://github.com/RadeonOpenCompute/hcc

**Comment by yxsamliu** [comment]
I checked out a clean hcc and built it, but still got two failures:
********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 1119.63s
********************
Failing Tests (2):
    HCC :: Unit/AmpMath/amp_math_exp_precise_math.cpp
    HCC :: Unit/Copy/copy.cpp

  Expected Passes    : 733
  Expected Failures  : 32
  Unexpected Failures: 2

I suspect either it is my card issue or base driver issue.

**Comment by yxsamliu** [comment]
what base driver did you use?

**Comment by scchan** [comment]
I use the the latest 1.6 public binaries

**Comment by whchung** [comment]
@yxsamliu i believe @scchan and i are all using `1.6.4`, `4.11.0-kfd-compute-rocm-rel-1.6-180` now.

**Comment by yxsamliu** [comment]
I installed the public rocm 1.6 and got almost half of tests failing with "There is no device can be used to do the computation". Did you see such issue before?

**Comment by scchan** [comment]
what does `/opt/rocm/bin/rocm_agent_enumerator -t GPU` return?

**Comment by yxsamliu** [comment]
Finally got all tests passing with hcc ToT.
-- Testing: 767 tests, 4 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 1132.36s
  Expected Passes    : 735
  Expected Failures  : 32

The previous failure seems due to rocm-dev dependent packages. After I remove them and reinstall rocm-dev, all tests passing.

I will do a run with the merge again.

**Comment by yxsamliu** [comment]
The merge branch passes all tests:
-- Testing: 767 tests, 4 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 1122.52s
  Expected Passes    : 735
  Expected Failures  : 32

**Review by scchan — APPROVED** [review]

**Pull request merged**
