### PR TITLE
Clang tot upgrade

### PR DESCRIPTION
**Pull request by vpykhtin**
Update to the clang's ToT. Fix for new ToolSelector class is included and require testing. This merge require llvm amd-common->amd-hcc merge which is pull requisted either.

Preliminary merge and require testing, I'm opening this pull request to make it visible.

### CODE REVIEW

**Comment by vpykhtin** [comment]
It's a bit early to post this pull request until other parts are ok.

**Comment by whchung** [comment]
@vpykhtin as this is a rather important PR, could you isolate your changes to somewhere like gist?

**Comment by vpykhtin** [comment]
Ok, I'll try, never did this before. BTW I need to fix more things before, I had other build failures yesterday evening.

**Comment by vpykhtin** [comment]
Jack, I read about gist: it's a mean to share code snippets? How to isolate such a big change into gist?

**Comment by whchung** [comment]
Please just post your commit wrt ToolSelector there. Nothing else. For the entire PR they can probably go to a separate branch before we decide to merge them.

**Comment by vpykhtin** [comment]
Well I submitted it as a separate change https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/10/commits/b019cade231ec12c0093bd5910af155fb201645e, provided that these called functions (IsHCHostAssembleJobAction, IsHCKernelAssembleJobAction etc.) are in the Driver.cpp (as it was before).

ToolSelector is just a refactoring of previous selectToolForJob routine, it has the same logic. I assume I preserved our logic too.

**Comment by whchung** [comment]
I think we can understand better after you solve the other pieces (llvm/lld), and be able to build the whole HCC compiler. I'm not very sure if commit #b019cad itself would provide the cure, given the fact ToolSelector has rather dramatic interface change from selectToolForJob.

**Pull request closed without merging**
