### PR TITLE
Make atomic codegen address space correct

### PR DESCRIPTION
**Pull request by AlexVlx**

### CODE REVIEW

**Comment by yxsamliu** [comment]
Normally __opencl_atomic_* should accept global/private/local pointers and translated to atomic instructions without addrspacecast. Do you have a simple test to demonstrate the issue.

**Comment by AlexVlx** [comment]
@yxsamliu thank you for the feedback. Please consider the following, for an example:
    - building Debug HCC with the following branches:
       - https://github.com/RadeonOpenCompute/hcc/tree/feature_remove_whitelist
       - https://github.com/RadeonOpenCompute/llvm/tree/feature-amd-hcc-remove-erasenonkernel
       - https://github.com/RadeonOpenCompute/hcc-clang-upgrade/tree/feature_remove_whitelist
This will fail when building ROCDL, with the assert in llvm/lib/IR/Instructions.cpp on line 2579 firing due to line 32 in https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/ockl/src/hsaqs.cl. You will observe in the generated IR that the issue is due to alloca-ing a temporary atomic_ulong type (which is in global) and just trying to bitcast it into a (flat / generic) pointer to a primitive i64. Note that in the context of the HC language this is correct conceptually, as our invariant is that all pointers point to flat. Hence, it appears that we should in general use CreatePointerBitCastOrAddrSpaceCast and not naked bit casts, when dealing with pointers (we may choose to optimise this later once everything is robust / correct). Please let me know if you can replicate.

**Comment by yxsamliu** [comment]
I got build failure when trying to build with the following branches:

- https://github.com/RadeonOpenCompute/hcc/tree/feature_remove_whitelist
- https://github.com/RadeonOpenCompute/llvm/tree/feature-amd-hcc-remove-erasenonkernel
- https://github.com/RadeonOpenCompute/hcc-clang-upgrade/tree/feature_remove_whitelist

-- Configuring done
CMake Error at compiler/cmake/modules/AddLLVM.cmake:1188 (add_dependencies):
  The dependency target "llvm-readelf" of target "check-all" does not exist.
Call Stack (most recent call first):
  compiler/CMakeLists.txt:929 (add_lit_target)


CMake Error at compiler/cmake/modules/AddLLVM.cmake:1188 (add_dependencies):
  The dependency target "llvm-readelf" of target "check-lld" does not exist.
Call Stack (most recent call first):
  compiler/cmake/modules/AddLLVM.cmake:1209 (add_lit_target)
  compiler/tools/lld/test/CMakeLists.txt:44 (add_lit_testsuite)

what branches and commits do you use for other submodules?

Another question? Does this issue only happen when building with these branches?

**Comment by yxsamliu** [comment]
Is it possible to have a simple test to demonstrate this issue? To me it seems that line 1172 of CGAtomics.cpp should not be reached at all for HCC. I suspect there may be some other issue causing it to be reached.

**Comment by AlexVlx** [comment]
@yxsamliu just to verify II've built and reproed the issue from a clean sheet just now. Please use the following branches:
    - hcc - feature_remove_whitelist
    - clang - feature_remove_whitelist
    - clang-tools-extra - amd-hcc
    - llvm - feature-amd-hcc-remove-erasenonkernel
    - compiler-rt - amd-hcc
    - lld - amd-hcc
    - rocdl - master
As for the second point about HCC not reaching that point at all, do keep in mind that the point of this whole exercise is to emit code for as many things as possible, which gets removed from the accelerator LLVMIR Module iff it is not referenced from a [[hc]] context. This is different from what we are doing now (and what exposes bugs such as this one).

**Comment by scchan** [comment]
@AlexVlx is this related to the issue where the address space deduction optimization incorrectly turning a generic address space pointer, which was passed to an atomic function, into private address space?

**Comment by AlexVlx** [comment]
@scchan no it is not (and that's not really an issue IMHO, the issue is that we do the wrong thing with said pointer after it is deduced as private, but different tale for different day:) ). This is related to the fact that with whitelist removal certain pieces of code that would've been discarded (e.g. functions without [[hc]] and without any presence on the manual whitelist) will now be emitted on the accelerator path (in this case, the function in ROCDL I outlined would have been ignored, but with the whitelist removal it gets emitted). This exercises the customised bits that we have there, such as the entire address space ballet and sometimes outlines parts of Clang that were not properly (IMHO) aligned with that design decision - I think that when targeting HC, at no point in the FE are we in a good position to just use a bitcast for pointers, by default, but should always consider that an addrspace_cast may be needed. CGAtomic.cpp didn't quite meet that requirement, hence the issue.

**Comment by yxsamliu** [comment]
Alex, did this issue happen when compiling rocdl, or did it happen when compiling some hcc source code?

Thanks.

**Comment by AlexVlx** [comment]
Hi Sam - as per the initial PR description "This will fail when building ROCDL, with the assert in llvm/lib/IR/Instructions.cpp on line 2579 firing due to line 32 in https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/ockl/src/hsaqs.cl [...]". Thank you.

**Comment by yxsamliu** [comment]
Hi Alex,
That file is an OpenCL source code, right? The LLVM value for OpenCL is supposed to have correct address space at the point of creation. If address space mismatch happens, we need to study case by case.

Do you have the command line which emits the compilation error? It should be printed out if you use make VERBOSE=1 to build rocdl.

**Pull request merged**
