### PR TITLE
Fix SWDEV-105106: make pow2 padding with ints

### PR DESCRIPTION
**Pull request by vpykhtin**
This fix use scalar int types for padding when possible instead of char[n]. This workarounds problem in SWDEV-105106 with array types.

### CODE REVIEW

**Comment by whchung** [comment]
@vpykhtin I've got a couple of questions in this pull request:

1. this should be applied after #6 is applied, right?
2. would this make SWDEV-105106 go away? If not, could you briefly explain what the next issue is?

**Comment by vpykhtin** [comment]
1. Well, its not connected with #6, it can be applied independently.
2. I'll try, it require further investigation.

It only fixes issue with bool [4] insertions for padding.

**Comment by whchung** [comment]
let me merge #6 first, I'll keep this one open after more information wrt SWDEV-105106 is known.

**Comment by vpykhtin** [comment]
Jack, in the meantime, could you please run some tests with my fix?

**Comment by whchung** [comment]
@vpykhtin After some studies in `CGRecordLayoutBuilder` I think the issue is not related to how paddings are computed, but on why we have paddings in the first place. The crux of the issue lies in `CGRecordLowering::getSize()` and `CGRecordLowering::getAlignment()`. They use `DataLayout` to check the width and alignment for a given `Type`, but in this case we really should consult `TargetInfo` where more information have be defined there.

**Pull request closed without merging**
