### PR TITLE
[HCC] Get rid of static bool IsCXXAMP(...) method in class clang::driver::Driver

### PR DESCRIPTION
**Pull request by emankov**
IsCXXAMP(...) method was replaced on conditions with lambda in place. No regressions.

### CODE REVIEW

**Review by whchung — APPROVED** [review]
LGTM

**Comment by whchung** [comment]
I'd like to request @scchan to make one extra pass of review before taking this PR.

**Comment by emankov** [comment]
Ooohh, sorry, I've already merged :( Anyway it looks like lambdas might be avoided as well: just awaiting tests' finishing and will send another PR for review.

**Review by scchan — COMMENTED** [review]
LGTM

**Pull request merged**
